/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#3f2300",
        "on-secondary": "#640039",
        "error-container": "#93000a",
        "inverse-on-surface": "#313032",
        "outline-variant": "#494454",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#673d00",
        "secondary": "#ffb0cd",
        "surface-bright": "#39393b",
        "secondary-fixed": "#ffd9e4",
        "inverse-surface": "#e5e1e4",
        "primary-fixed-dim": "#d0bcff",
        "surface-container": "#201f21",
        "primary": "#d0bcff",
        "on-primary-fixed": "#23005c",
        "on-secondary-fixed-variant": "#8c0053",
        "tertiary-container": "#ca801e",
        "secondary-container": "#aa0266",
        "tertiary-fixed-dim": "#ffb869",
        "on-primary": "#3c0091",
        "surface-container-low": "#1c1b1d",
        "on-tertiary-fixed": "#2c1700",
        "on-secondary-fixed": "#3e0022",
        "on-secondary-container": "#ffbad3",
        "on-background": "#e5e1e4",
        "surface-container-high": "#2a2a2c",
        "on-primary-container": "#340080",
        "primary-container": "#a078ff",
        "surface-variant": "#353437",
        "background": "#131315",
        "on-surface": "#e5e1e4",
        "surface-dim": "#131315",
        "on-primary-fixed-variant": "#5516be",
        "surface-tint": "#d0bcff",
        "tertiary": "#ffb869",
        "surface": "#131315",
        "inverse-primary": "#6d3bd7",
        "tertiary-fixed": "#ffdcbb",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#cbc3d7",
        "outline": "#958ea0",
        "surface-container-lowest": "#0e0e10",
        "secondary-fixed-dim": "#ffb0cd",
        "on-tertiary": "#482900",
        "on-error": "#690005",
        "primary-fixed": "#e9ddff",
        "surface-container-highest": "#353437"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "card-padding": "24px",
        "button-padding-y": "12px",
        "unit": "4px",
        "margin-mobile": "16px",
        "button-padding-x": "24px",
        "margin-desktop": "64px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Outfit"],
        "headline-xl": ["Outfit"],
        "body-lg": ["Inter"],
        "headline-md": ["Outfit"],
        "headline-lg": ["Outfit"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
